### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by rgarvey93** [belangeo/pyo#108]
Continuously running into this issue, first wxPython is not running. Secondly, filter.ctrl is running into a fatal error, any advice?

`=== Output log of process "FM_synth.py", launched: "01 Nov 2017 13:11:32" ===
pyo version 0.8.7 (uses double precision)

WxPython is not found for the current python version.
Pyo will use a minimal GUI toolkit written with Tkinter (if available).
This toolkit has limited functionnalities and is no more
maintained or updated. If you want to use all of pyo's
GUI features, you should install WxPython, available here:
http://www.wxpython.org/

Traceback (most recent call last):
  File "C:\Users\Ryan\.epyo\epyo_tempfile.py", line 25, in <module>
    filter.ctrl()
  File "C:\Python27\lib\site-packages\pyolib\filters.py", line 155, in ctrl
    PyoObject.ctrl(self, map_list, title, wxnoserver)
  File "C:\Python27\lib\site-packages\pyolib\_core.py", line 1516, in ctrl
    createCtrlWindow(self, map_list, title, wxnoserver)
  File "C:\Python27\lib\site-packages\pyolib\_widgets.py", line 241, in createCtrlWindow
    f = PyoObjectControl(win, obj, map_list)
  File "C:\Python27\lib\site-packages\pyolib\_tkwidgets.py", line 198, in __init__
    setattr(self._obj, key, self._sigs[key])
  File "C:\Python27\lib\site-packages\pyolib\filters.py", line 183, in type
    def type(self, x): self.setType(x)
  File "C:\Python27\lib\site-packages\pyolib\filters.py", line 146, in setType
    pyoArgsAssert(self, "i", x)
  File "C:\Python27\lib\site-packages\pyolib\_core.py", line 476, in pyoArgsAssert
    raise PyoArgumentTypeError(err % (i, name, expected, argtype))
pyolib._core.PyoArgumentTypeError: bad argument at position 0 to "Biquad" (integer expected, got <class 'pyolib.controls.SigTo'>)
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
`

**Comment by belangeo** [comment]
Hi,
Thanks for reporting this. There was an issue with Tk sliders when an object has a dataOnly parameter. It's fixed in the sources. But, if you want to use all GUI features that come with pyo, you should really install wxpython (3.0.2.0 for python 2.7, phoenix for python 3). Not all GUIs are available with Tk.
