### ISSUE TITLE
Segfault during python exit from Pyo  

### ISSUE THREAD

**Issue by bielaszewski** [belangeo/pyo#110]
A seg fault occurs during python2.7 exit on linux using build from commit  (code chg for issue #109) e4a53c8.
This looks quite a bit like the same problem reported on the discussion board by Tiago Bortoletto Vaz on Nov 5, 2017.

this minimal.py  program will reproduce the issue:
```
from pyo import *
s=Server( audio='jack' ).boot()
s.start()
#s.gui()
r=input( 'type 0<cr> to terminate')
```
Steps:
1) start python2.7 under GDB:   gdb python
2) at gdb prompt:  run minimal.py
3) at input prompt enter:   0<cr>
4) debugger reports: 
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff7870bd6 in _int_free (av=0x7ffff7bb4b20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4015
```
5) request stack trace from gdb: 
```
 (gdb) bt
#0  0x00007ffff7870bd6 in _int_free (av=0x7ffff7bb4b20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4015
#1  0x00007ffff7874abc in __GI___libc_free (mem=<optimized out>) at malloc.c:2969
#2  0x00000000004b54e5 in ?? ()
#3  0x00000000004a0d22 in PyDict_SetItem ()
#4  0x0000000000502bf3 in _PyModule_Clear ()
#5  0x00000000005028f2 in PyImport_Cleanup ()
#6  0x0000000000500489 in Py_Finalize ()
#7  0x0000000000526268 in Py_Exit ()
#8  0x0000000000523673 in ?? ()
#9  0x0000000000522f66 in PyErr_PrintEx ()
#10 0x00007ffff3704355 in wxPyCallback::EventThunker(wxEvent&) () from /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core_.x86_64-linux-gnu.so
```
regards,
John B

**Comment by bielaszewski** [comment]
Segfault during exit fixed in commit 9d0d04cc33c
