### ISSUE TITLE
Expected in: flat namespace

### ISSUE THREAD

**Issue by chaosprint** [belangeo/pyo#131]
>>> import pyo

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Users/chaosprint/anaconda3/lib/python3.6/pyo.py", line 21, in <module>

    import pyolib.analysis as analysis

  File "/Users/chaosprint/anaconda3/lib/python3.6/pyolib/analysis.py", line 32, in <module>

    from ._core import *

  File "/Users/chaosprint/anaconda3/lib/python3.6/pyolib/_core.py", line 58, in <module>

    from _pyo import *

ImportError: dlopen(/Users/chaosprint/anaconda3/lib/python3.6/_pyo.so, 2): Symbol not found: 

__Py_ZeroStruct

  Referenced from: /Users/chaosprint/anaconda3/lib/python3.6/_pyo.so

  Expected in: flat namespace

 in /Users/chaosprint/anaconda3/lib/python3.6/_pyo.so

**Comment by belangeo** [comment]
You are likely using an incompatible version of Python (for instance, the extension library was compiled against Python 2, while the interpreter is running on top of some version of Python 3, or vice versa). How did you installed pyo?

**Comment by belangeo** [comment]
Closing this issue as this will not be a problem no more with pip installation.
