### ISSUE TITLE
FFT seems broken

### ISSUE THREAD

**Issue by ntuckerxx** [belangeo/pyo#138]
I'm unable to create any instances of FFT, even exactly as shown in the example comments, because `__init__` calls self.play(), which seems to have a prerequisite that `self._base_objs` is initialized (which  it isn't).  I can't see how this could possibly work based on my reading of the code.

```$ python3
Python 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyo import *
>>> s = Server().boot()
Pyo warning: Portmidi warning: no midi device found!
Portmidi closed.
>>> a = Noise(.25).mix(2)
>>> fin = FFT(a, size=1024, overlaps=4, wintype=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyo-0.9.2-py3.7-macosx-10.13-x86_64.egg/pyo/lib/fourier.py", line 127, in __init__
    self.play()
  File "/usr/local/lib/python3.7/site-packages/pyo-0.9.2-py3.7-macosx-10.13-x86_64.egg/pyo/lib/fourier.py", line 187, in play
    self._autoplay(dur, delay)
  File "/usr/local/lib/python3.7/site-packages/pyo-0.9.2-py3.7-macosx-10.13-x86_64.egg/pyo/lib/_core.py", line 986, in _autoplay
    if self.getServer().getAutoStartChildren():
  File "/usr/local/lib/python3.7/site-packages/pyo-0.9.2-py3.7-macosx-10.13-x86_64.egg/pyo/lib/_core.py", line 869, in getServer
    return self._base_objs[0].getServer()
IndexError: list index out of range
>>>```

**Comment by belangeo** [comment]
Thanks for reporting! It's fixed in the sources. Can you confirm please?

**Comment by ntuckerxx** [comment]
Confirmed fixed. Thanks for the quick response.
