### ISSUE TITLE
Pyo on Raspberry Pi

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#156]
I am trying to get Pyo running on my Raspberry Pi, but I do not know what server boot parameters I need. I tried to some info with pa_list_devices(), but that gave me:pa_list_devices()
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
AUDIO devices:
0: OUT, name: bcm2835 ALSA: - (hw:0,0), host api index: 0, default sr: 44100 Hz, latency: 0.005805 s
1: OUT, name: bcm2835 ALSA: IEC958/HDMI (hw:0,1), host api index: 0, default sr: 44100 Hz, latency: 0.005805 s
2: IN, name: C-Media USB Headphone Set: Audio (hw:1,0), host api index: 0, default sr: 44100 Hz, latency: 0.008685 s
2: OUT, name: C-Media USB Headphone Set: Audio (hw:1,0), host api index: 0, default sr: 44100 Hz, latency: 0.008707 s
3: IN, name: sysdefault, host api index: 0, default sr: 48000 Hz, latency: 0.021333 s
3: OUT, name: sysdefault, host api index: 0, default sr: 48000 Hz, latency: 0.021333 s
4: OUT, name: front, host api index: 0, default sr: 44100 Hz, latency: 0.008685 s
5: OUT, name: surround40, host api index: 0, default sr: 44100 Hz, latency: 0.008685 s
6: OUT, name: iec958, host api index: 0, default sr: 44100 Hz, latency: 0.008685 s
7: IN, name: spdif, host api index: 0, default sr: 44100 Hz, latency: 0.008685 s
7: OUT, name: spdif, host api index: 0, default sr: 44100 Hz, latency: 0.008707 s
8: OUT, name: dmix, host api index: 0, default sr: 48000 Hz, latency: 0.021333 s
9: IN, name: default, host api index: 0, default sr: 44100 Hz, latency: 0.008685 s
9: OUT, name: default, host api index: 0, default sr: 44100 Hz, latency: 0.008707 s

**Comment by zappfinger** [comment]
Now I made My USB card the default and started up jackd. Got other errors now, trying the FM example:
Pyo warning: Portaudio input device `system` has fewer channels (1) than requested (2).
Portaudio error in Pa_OpenStream: Invalid sample rate
Pyo error: From portaudio, Invalid sample rate
Portaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
Portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized
Pyo error: 
Server not booted.
Traceback (most recent call last):
  File "03-fm-generators.py", line 24, in <module>
    fm1 = FM(carrier=250, ratio=[1.5,1.49], index=10, mul=0.3)
  File "/usr/lib/python2.7/dist-packages/pyo-0.9.2-py2.7-linux-armv7l.egg/pyo/lib/generators.py", line 559, in __init__
    PyoObject.__init__(self, mul, add)
  File "/usr/lib/python2.7/dist-packages/pyo-0.9.2-py2.7-linux-armv7l.egg/pyo/lib/_core.py", line 1148, in __init__
    PyoObjectBase.__init__(self)
  File "/usr/lib/python2.7/dist-packages/pyo-0.9.2-py2.7-linux-armv7l.egg/pyo/lib/_core.py", line 836, in __init__
    raise PyoServerStateException("The Server must be booted before "
pyo.lib._core.PyoServerStateException: The Server must be booted before creating any audio object.

**Comment by zappfinger** [comment]
After apt-get update and upgrade, installed portaudio, started jackd, and it works now with the following:
s=Server(sr=44100, nchnls=2, buffersize=256, duplex=1, audio='jack', jackname='pyo') 
s.boot()
