### ISSUE TITLE
SfPlayer doesn't work 

### ISSUE THREAD

**Issue by Manu197-pn** [belangeo/pyo#250]
I do not succeed in using SfPlayer. When I run the example or any other program I get the following error.
I am using Mac OS 12.6. Python 3.1 
It is working when loading the file in ram and reading the table.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/emmanuel/PycharmProjects/pythonProject2/venv/lib/python3.10/site-packages/pyo/examples/04-soundfiles/01-read-from-disk.py", line 24, in <module>
    sf = SfPlayer(path, speed=[1, 0.995], loop=True, mul=0.4).out()
  File "/Users/emmanuel/PycharmProjects/pythonProject2/venv/lib/python3.10/site-packages/pyo/lib/players.py", line 118, in __init__
    SfPlayer_base(
SystemError: <class '_pyo.SfPlayer_base'> returned a result with an exception set

**Comment by belangeo** [comment]
Can you print the _path_ variable and verify if "transparent.aif" is in the given directory?
