### ISSUE TITLE
win10 getting requirements to build wheel did not run successfully

### ISSUE THREAD

**Issue by nostalgia-junkie** [belangeo/pyo#278]
i am an absolute beginner to all of this, please forgive my ignorance

initially  install cecilia5 with the windows installer, but kept getting a codec error. deleting the .cecilia5 folder didn't help. someone in an issue thread suggested to run from the latest sources, so i uninstalled cecilia and began installing.
i have python 3.12.4, numpy 2.0.0, wxpython 4.2.1, and git 2.45.2.windows.1
pyo wont install because of this error:

 running egg_info
      writing pyo.egg-info\PKG-INFO
      writing dependency_links to pyo.egg-info\dependency_links.txt
      writing entry points to pyo.egg-info\entry_points.txt
      writing top-level names to pyo.egg-info\top_level.txt
      reading manifest file 'pyo.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\Andrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Andrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 419, in <module>
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 595, in add_defaults
          self.read_manifest()
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\command\sdist.py", line 203, in read_manifest
          self.filelist.append(line)
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 487, in append
          path = convert_path(item)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andrew\AppData\Local\Temp\pip-build-env-i13mbbhk\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 132, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/usr/local/Cellar/flac/1.4.2/lib/libFLAC.12.dylib' cannot be absolute
      [end of output]

i have no idea what i did wrong, other than use the wrong version of python maybe? did uninstalling and reinstalling cecilia and python mess up something? at this point i just want it to work for the sake of solving the puzzle. again, please forgive my ignorance.

**Comment by belangeo** [comment]
At this moment, pyo doesn't have wheels for 3.12, it only supports up to 3.11... Next release (coming soon) will support 3.12 and 3.13. You can work this out easily by installing python 3.11.
