### ISSUE TITLE
metadata-generation-failed (py 3.8, windows 10)

### ISSUE THREAD

**Issue by McPxl** [belangeo/pyo#279]
I first tried to install pyo with python 3.12 then realized that that version wasn't supported ( kept getting stuck at the build wheel step) so I switched to 3.8.
And now I keep getting this error

> C:\Users\nelly\pyo>py -3.8 -m pip install --user pyo
Collecting pyo
  Using cached pyo-1.0.5.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × **Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      C:\Users\nelly\AppData\Local\Temp\pip-build-env-3p37gqgz\overlay\Lib\site-packages\setuptools\build_meta.py:497: SetuptoolsDeprecationWarning: Running `setup.py` directly as CLI tool is deprecated.**
      !!

              ********************************************************************************
              Please avoid using `sys.exit(0)` or similar statements that don't fit in the paradigm of a configuration file.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        super().run_setup(setup_script=setup_script)
      setup.py is no more configured to compile on 32-bit windows.
      Traceback (most recent call last):
        File "C:\Users\nelly\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\nelly\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\nelly\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\nelly\AppData\Local\Temp\pip-build-env-3p37gqgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 370, in prepare_metadata_for_build_wheel
          self._bubble_up_info_directory(metadata_directory, ".egg-info")
        File "C:\Users\nelly\AppData\Local\Temp\pip-build-env-3p37gqgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 339, in _bubble_up_info_directory
          info_dir = self._find_info_directory(metadata_directory, suffix)
        File "C:\Users\nelly\AppData\Local\Temp\pip-build-env-3p37gqgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 350, in _find_info_directory
          assert len(candidates) == 1, f"Multiple {suffix} directories found"
      **AssertionError: Multiple .egg-info directories found**
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Can't figure out a workaround.
Thank you

**Comment by belangeo** [comment]
What's your system architecture? pip should not have tried to build from sources, but use the wheel for 3.8 from pypi.org instead...

**Comment by belangeo** [comment]
Oh, pip used the cached tar download:

> Using cached pyo-1.0.5.tar.gz (5.2 MB)

You should clear the cache first.

Next release of pyo (coming soon) will have wheels for 3.12 and 3.13.

**Comment by belangeo** [comment]
Nothing to do.
