### ISSUE TITLE
Can't start on Ubuntu 14.04

### ISSUE THREAD

**Issue by dantheman39** [belangeo/pyo#63]
Hello! I installed with no issues following the instructions here: http://ajaxsoundstudio.com/pyodoc/compiling.html on Ubuntu 14.04, but I cannot successfully start a server. (Ok, well, one issue is that I think there's a typo in the Ubuntu instructions: libjack-jack2-dev should be libjack-jackd2-dev, right?) I've tried several things after trawling the web for a few hours, among them: 
    -making sure I had the most up to date version (I have 0.7.6), 
    -making sure I installed with --use-jack, 
    -making sure permissions are correct by running dpkg --reconfigure
    -including my user in the audio group and rebooting
    -I also installed jackd2, but this has not made a difference.
    -starting the server with the audio="jack" option (this gives a different error, will post below).

If I run this:

    ~$ python
    >>> from pyo import *
    pyo version 0.7.6 (uses single precision)
    >>> s = Server().boot()

I get this error:

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

And if I run with the audio="jack" option: (s = Server(audio="jack").boot() ), I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pyolib/server.py", line 122, in __init__
    self._server._setDefaultRecPath(os.path.join(os.path.expanduser("~"), "pyo_rec.wav"))
AttributeError: 'NoneType' object has no attribute '_setDefaultRecPath'

Any help would greatly be appreciated. Thanks, 

Dan

**Comment by dantheman39** [comment]
Well, I woke up today and it worked! I'm not sure what of the steps above did it. I know using audio="jack" is necessary, and I suspect that it was installing jackd2. Not sure if it was supposed to have been installed, but it wasn't. If the problem reappears, I will reopen.
