### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by elfh78** [belangeo/pyo#98]
Hello! I installed pyo for python2.7 on Windows 7 64bit and get the following error after trying to run first example:
Traceback (most recent call last):
  File "C:\Users\ielfimov\.epyo\epyo_tempfile.py", line 4, in <module>
    from pyo import *
  File "C:\Python27\lib\site-packages\pyo.py", line 21, in <module>
    import pyolib.analysis as analysis
  File "C:\Python27\lib\site-packages\pyolib\analysis.py", line 32, in <module>
    from ._core import *
  File "C:\Python27\lib\site-packages\pyolib\_core.py", line 57, in <module>
    from _pyo import *
ImportError: DLL load failed: Module not found.

my system is in Russian, so actual error message was translated to english, could be a bit different on English systems.

**Comment by belangeo** [comment]
Hi,
Can you try this installer:

[https://www.dropbox.com/s/55zcszqcuicrm36/pyo_0.8.6_py2.7_setup.exe?dl=0](https://www.dropbox.com/s/55zcszqcuicrm36/pyo_0.8.6_py2.7_setup.exe?dl=0)

There is an error in windows dependencies in version 0.8.6. I'll build new installers soon...

**Comment by belangeo** [comment]
Fixed in sources. Will be in the next release (0.8.7).
